package ipl;

public enum FeatureEnum {
    BATTING_AVERAGE,BOWLING_AVERAGE,STRIKING_RATES,MAX_SIXES_AND_FOURS,BEST_AVERAGE_WITH_STRIKING_RATE,
    MAX_RUNS_WITH_BEST_AVERAGE, STRIKING_RATE_WTIH_MAX_SIXES_FOURS,ECONOMY,STRIKING_RATE_WITH_MAX_FOUR_AND_FIVE_WICKETS,
    BOWLING_AVERAGE_WITH_STRIKING_RATE,WICKETS_WITH_BOWLING,BATTING_AVERAGE_WITH_BLOWING_AVERAGE,
    RUNS_WITH_WICKETS
}
